# Generated by Django 2.1.5 on 2019-02-12 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(help_text='Nombres', max_length=100, verbose_name='Nombres')),
                ('last_name_p', models.CharField(help_text='Apellido Paterno', max_length=100, verbose_name='Apellido Paterno')),
                ('last_name_m', models.CharField(help_text='Apellido Materno', max_length=100, verbose_name='Apellido Materno')),
                ('mobile_number', models.CharField(blank=True, help_text='Número de Teléfono Celular', max_length=20, verbose_name='Celular')),
                ('phone', models.CharField(blank=True, help_text='Número de Teléfono Fijo o de Oficina', max_length=20, verbose_name='Teléfono')),
                ('born_date', models.DateField(blank=True, help_text='Fecha de Nacimiento', null=True, verbose_name='Nacimiento')),
                ('email', models.EmailField(blank=True, help_text='Correo Electrónico', max_length=40, verbose_name='Email')),
                ('registerDate', models.DateField(default=django.utils.timezone.now, help_text='Fecha de Registro', verbose_name='Fecha de Registro')),
                ('dni', models.CharField(blank=True, help_text='Número de DNI', max_length=8, verbose_name='DNI')),
            ],
            options={
                'ordering': ['names'],
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre', max_length=50, verbose_name='Nombre del TIpo de Perfil')),
                ('description', models.CharField(help_text='Descripción', max_length=100, verbose_name='Descripción')),
                ('smallChar', models.CharField(help_text='Small Code', max_length=1, verbose_name='Small Code')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profileType',
            field=models.ForeignKey(help_text='Tipo de Perfil', on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileType', verbose_name='Tipo de Perfil'),
        ),
    ]
