# Generated by Django 2.1.5 on 2019-02-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Carrera', max_length=10, verbose_name='Código Carrera')),
                ('name', models.CharField(help_text='Nombre de la Carrera', max_length=100, verbose_name='Nombre Carrera')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Escuela', max_length=10, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre de Escuela', max_length=80, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Institución', max_length=10, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre de Institución', max_length=80, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(help_text='Carrera', on_delete=django.db.models.deletion.CASCADE, to='institutions.Career', verbose_name='Carrera')),
                ('faculty', models.ForeignKey(help_text='Facultad', on_delete=django.db.models.deletion.CASCADE, to='institutions.Faculty', verbose_name='Facultad')),
            ],
            options={
                'ordering': ['career'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Modalidad', max_length=10, verbose_name='Código Modalidad')),
                ('description', models.CharField(help_text='Descripción de la Modalidad', max_length=100, verbose_name='Descripción')),
                ('shortDescription', models.CharField(help_text='Descripción corta de la Modalidad', max_length=100, verbose_name='Descripción Corta')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Sede', max_length=10, verbose_name='Código')),
                ('description', models.CharField(help_text='Descripción', max_length=100, verbose_name='Descripción')),
                ('shortDescription', models.CharField(help_text='Descripción Corta', max_length=25, verbose_name='Descripción Corta')),
                ('institution', models.ForeignKey(help_text='Institución', on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution', verbose_name='Institución')),
            ],
            options={
                'ordering': ['shortDescription'],
            },
        ),
        migrations.AddField(
            model_name='institutionstar',
            name='modality',
            field=models.ForeignKey(help_text='Modalidad', on_delete=django.db.models.deletion.CASCADE, to='institutions.Modality', verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='institutionstar',
            name='subsidiary',
            field=models.ForeignKey(help_text='Filial', on_delete=django.db.models.deletion.CASCADE, to='institutions.Subsidiary', verbose_name='Filial'),
        ),
    ]
