# Generated by Django 2.1.5 on 2019-02-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del Curso', max_length=10, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre del Curso', max_length=80, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Grupo', max_length=10, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre de Categoría', max_length=80, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Frecuencia', max_length=10, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre de Frecuencia', max_length=80, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del Curso', max_length=10, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre del Curso', max_length=80, verbose_name='Nombre')),
                ('year', models.CharField(help_text='Año', max_length=8, verbose_name='Año')),
                ('institution', models.ForeignKey(blank=True, help_text='Institución', null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution', verbose_name='Institución')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoursePlanActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del Plan Activo', max_length=10, verbose_name='Código')),
                ('course', models.ForeignKey(help_text='Curso', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Curso')),
                ('coursePlan', models.ForeignKey(help_text='Plan Curricular', on_delete=django.db.models.deletion.CASCADE, to='courses.CoursePlan', verbose_name='Plan Curricular')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Ciclo', max_length=10, verbose_name='Código')),
                ('description', models.CharField(help_text='Descripción del Ciclo', max_length=80, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startHour', models.TimeField(help_text='Hora de Inicio', verbose_name='Inicio')),
                ('endHour', models.TimeField(help_text='Hora de Inicio', verbose_name='Inicio')),
                ('academicHours', models.DecimalField(decimal_places=2, help_text='Horas Académicas)', max_digits=3, verbose_name='Horas Académicas')),
                ('cronologicHour', models.DecimalField(decimal_places=2, help_text='Horas Cronológicas', max_digits=3, verbose_name='Horas Cronológicas')),
            ],
            options={
                'ordering': ['startHour'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Sección', max_length=10, verbose_name='Código')),
                ('assign', models.CharField(help_text='Asignación', max_length=20, verbose_name='Asignación')),
                ('group', models.CharField(help_text='Grupo', max_length=20, verbose_name='Grupo')),
            ],
            options={
                'ordering': ['assign'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Turno', max_length=10, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre del Turno', max_length=80, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='courseplanactive',
            name='grade',
            field=models.ForeignKey(help_text='Ciclo', on_delete=django.db.models.deletion.CASCADE, to='courses.Grade', verbose_name='Ciclo'),
        ),
    ]
