# Generated by Django 2.1.5 on 2019-02-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('classRooms', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classRoom', models.ForeignKey(help_text='Aula', on_delete=django.db.models.deletion.CASCADE, to='classRooms.ClassRoom', verbose_name='Aula')),
            ],
            options={
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCategoryDetailHours', models.CharField(blank=True, help_text='Detalle de Horas de Categoría', max_length=30, null=True, verbose_name='Detalle de Horas de Categoría')),
                ('courseCategory', models.ForeignKey(help_text='Categoría de Curso', on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategory', verbose_name='Categoría de Curso')),
                ('courseFrequency', models.ForeignKey(help_text='Frecuencia del Curso', on_delete=django.db.models.deletion.CASCADE, to='courses.CourseFrequency', verbose_name='Frecuencia del Curso')),
            ],
            options={
                'ordering': ['coursePlanActive'],
            },
        ),
        migrations.AlterModelOptions(
            name='courseplanactive',
            options={'ordering': ['course']},
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='year',
            field=models.CharField(help_text='Año', max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='coursecategorydetail',
            name='coursePlanActive',
            field=models.ForeignKey(help_text='Plan Curricular Activo', on_delete=django.db.models.deletion.CASCADE, to='courses.CoursePlanActive', verbose_name='Plan Curricular Activo'),
        ),
        migrations.AddField(
            model_name='courseassignation',
            name='courseCategoryDetail',
            field=models.ForeignKey(help_text='Detalle de Categoría de Curso', on_delete=django.db.models.deletion.CASCADE, to='courses.CourseCategoryDetail', verbose_name='Detalle de Categoría de Curso'),
        ),
        migrations.AddField(
            model_name='courseassignation',
            name='lesson',
            field=models.ForeignKey(help_text='Clase', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='courseassignation',
            name='section',
            field=models.ForeignKey(help_text='Sección', on_delete=django.db.models.deletion.CASCADE, to='courses.Section', verbose_name='Sección'),
        ),
        migrations.AddField(
            model_name='courseassignation',
            name='teacher',
            field=models.ForeignKey(help_text='Profesor', on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher', verbose_name='Profesor'),
        ),
    ]
