# Generated by Django 2.1.5 on 2019-02-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190216_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['grade']},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='code',
        ),
        migrations.AddField(
            model_name='coursefrequency',
            name='days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Cantidad de Días', verbose_name='Días'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ciclo', verbose_name='Ciclo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='day',
            field=models.CharField(default=0, help_text='Día', max_length=15, verbose_name='Día'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='assign',
            field=models.CharField(help_text='Asignación', max_length=6, verbose_name='Asignación'),
        ),
        migrations.AlterField(
            model_name='section',
            name='group',
            field=models.CharField(help_text='Grupo', max_length=2, verbose_name='Grupo'),
        ),
    ]
