# Generated by Django 2.1.5 on 2019-02-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de Aula', max_length=10, verbose_name='Código')),
                ('description', models.CharField(help_text='Descripción de Aula', max_length=140, verbose_name='Descripción')),
                ('capacity', models.PositiveSmallIntegerField(help_text='Capacidad del Aula', verbose_name='Capacidad')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del Tipo de Aula', max_length=140, verbose_name='Descripción')),
                ('smallCharCode', models.CharField(help_text='Código de Tipo de Aula', max_length=1, verbose_name='Código')),
            ],
            options={
                'ordering': ['smallCharCode'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='roomType',
            field=models.ForeignKey(help_text='Tipo de Aula', on_delete=django.db.models.deletion.CASCADE, to='classRooms.RoomType', verbose_name='Tipo de Aula'),
        ),
    ]
