# Generated by Django 2.1.5 on 2019-02-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del Curso', max_length=10, verbose_name='Código')),
                ('faculty', models.ForeignKey(help_text='Escuela', on_delete=django.db.models.deletion.CASCADE, to='institutions.Faculty', verbose_name='Escuela')),
                ('originSubsidiary', models.ForeignKey(help_text='Sede de Origen', on_delete=django.db.models.deletion.CASCADE, to='institutions.Subsidiary', verbose_name='Sede de Origen')),
                ('profile', models.ForeignKey(help_text='Perfil Enlazado', on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Perfil')),
            ],
            options={
                'ordering': ['profile'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del Salario', max_length=80, verbose_name='Nombre')),
                ('value', models.DecimalField(decimal_places=2, help_text='Salario', max_digits=8, verbose_name='Salario')),
                ('subsidiary', models.ForeignKey(help_text='Sede', on_delete=django.db.models.deletion.CASCADE, to='institutions.Subsidiary', verbose_name='Sede')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de Docente', max_length=80, verbose_name='Nombre')),
                ('description', models.CharField(help_text='Descripción del Tipo de Docente', max_length=100, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='teacherType',
            field=models.ForeignKey(help_text='Tipo de Docente', on_delete=django.db.models.deletion.CASCADE, to='teachers.TeacherType', verbose_name='Tipo de Docente'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherType',
            field=models.ForeignKey(help_text='Tipo de Profesor', on_delete=django.db.models.deletion.CASCADE, to='teachers.TeacherType', verbose_name='Tipo de Profesor'),
        ),
    ]
